name: Deploy Angular App to VPS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Set environment variables for build
        run: |
          echo "OPENAI_API_KEY_BLOG=${{ secrets.OPENAI_API_KEY_BLOG }}" >> $GITHUB_ENV
          echo "PGHOST=${{ secrets.PGHOST }}" >> $GITHUB_ENV
          echo "PGDATABASE=${{ secrets.PGDATABASE }}" >> $GITHUB_ENV
          echo "PGUSER=${{ secrets.PGUSER }}" >> $GITHUB_ENV
          echo "PGPASSWORD=${{ secrets.PGPASSWORD }}" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build Angular app
        run: npm run build
        env:
          OPENAI_API_KEY_BLOG: ${{ secrets.OPENAI_API_KEY_BLOG }}
          PGHOST: ${{ secrets.PGHOST }}
          PGDATABASE: ${{ secrets.PGDATABASE }}
          PGUSER: ${{ secrets.PGUSER }}
          PGPASSWORD: ${{ secrets.PGPASSWORD }}

      - name: Clean target directory on server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            sudo rm -rf /var/www/one-daily-blog/*

      - name: Ensure correct permissions on target directory
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            sudo mkdir -p /var/www/one-daily-blog
            sudo chown -R ${{ secrets.VPS_USER }}:$USER /var/www/one-daily-blog
            sudo chmod -R 775 /var/www/one-daily-blog

      - name: Deploy files via SSH
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "dist/one-daily-blog/*"
          target: "/var/www/one-daily-blog"

      - name: Deploy ecosystem.config.js
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "ecosystem.config.js"
          target: "/var/www/one-daily-blog"

      - name: Deploy and restart using PM2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /var/www/one-daily-blog
            pm2 startOrRestart ecosystem.config.js --env production --update-env
            sudo systemctl restart nginx
